"""Add moderation fields to testimonials

Revision ID: 4e4b675db3cd
Revises: 5e723a6e39dc
Create Date: 2025-07-29 01:13:17.484683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e4b675db3cd'
down_revision = '5e723a6e39dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonials', schema=None) as batch_op:
        batch_op.drop_column('is_featured')
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###
