"""Add Subscription model

Revision ID: ec135d7f2a27
Revises: ef670dc9f2f4
Create Date: 2025-07-28 23:48:22.929667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec135d7f2a27'
down_revision = 'ef670dc9f2f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscribed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('expires_at')
        batch_op.drop_column('subscribed_at')

    # ### end Alembic commands ###
